### ISSUE TITLE
Does not work in Safari

### ISSUE THREAD

**Issue by Rexios80** [flyinggiants/ScoreSaber-Rank-Panel#1] opened 2019-10-30 13:42 UTC
I don't know how much you care, but the extension doesn't load in Safari. All it shows is ":/". Also I'm not sure this is the right repo, but it's the only one I found.

**Comment by LucaVazz** [comment] 2019-10-30 20:14
Hello Rexios80,

you have found the right repo indeed, this is the source code behind the extension.

I'm aware of the issues in Safari and was incrementally trying to resolve them. 
However, I don't have access to an Apple device, so it is quite hard for me to test.
Would you be willing to tell me your Twitch Account name so I can add you as a beta tester to work towards a solution faster?

**Comment by Rexios80** [comment] 2019-10-30 21:23
Rexios85

**Comment by LucaVazz** [comment] 2019-12-16 21:03
Hey @Rexios80,

sadly I was busy with other things and could only now get around to investigate the issue in depth.
Hopefully I'll be able to push a new version for you to test soon.

( likely root cause: https://sentry.io/organizations/twitch-lv/issues/1078483169/ )

**Comment by LucaVazz** [comment] 2019-12-17 00:09
Hey @Rexios80,

indeed from my side, based on the collected error logging, this problem should be fixed now.

Can you please test it from your side? For this, please open Twitch and go to my channel `LVreg`. This channel has the new version of the extension visible for you (Twitch will prompt you to accept to use the unreleased version).

**Comment by LucaVazz** [comment] 2019-12-20 11:23
The new version was released yesterday, from the Error Analytics gathered the Extension now works fine in Safari. 
Marking the issue as closed, please comment if it re-appears on your side.

**Closed as completed** 2019-12-20 11:23 UTC
